import { Component } from '@angular/core';

function log(target, name, descriptor) {
  console.log(target,name,descriptor)
  // Store original function in a variable
  const original = descriptor.value
  // do some manipulation with a descriptor.value
  descriptor.value = function(...args) {
    console.log("Arguments", args, " where passed into this function")
    const result = original.apply(this, args)
    console.log("The result of the function is", result)
  
  }
  // return the descriptor
  return descriptor
}



@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'intro2angular';

  constructor() {
    console.log("this statement was generated by the constructor", this.aSimpleMethod(5))
  }

  @log
  aSimpleMethod(a){
    return a*a
  }
}
